# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    api.product_voter:
        class: ApiBundle\Security\ProductVoter
        tags:
            - { name: security.voter }
        public: false
