# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  api.product.class: ApiBundle\Manager\ProductManger
  api.product.entity_class: ApiBundle\Entity\Product
  api.user.class: ApiBundle\Manager\UserManager
  api.user.entity_class: ApiBundle\Entity\User

services:
    api.product_voter:
        class: ApiBundle\Security\ProductVoter
        tags:
            - { name: security.voter }
        public: false

    api.core_manager:
        abstract: true
        class: ApiBundle\Manager\CoreManager
        calls:
          - [ setEntityProperties, ["@doctrine.orm.default_entity_manager"] ]
          - [ setTranslator, [ "@translator" ] ]
          - [ setSession, [ "@session" ] ]

    api.product_manager:
        class: "%api.product.class%"
        arguments: [ "%api.product.entity_class%" ]
        parent: api.core_manager

    api.user_manager:
          class: "%api.user.class%"
          arguments: [ "%api.user.entity_class%" ]
          parent: api.core_manager