parameters:
  api.product.class: ApiBundle\Manager\ProductManger
  api.product.entity_class: ApiBundle\Entity\Product

services:
  api.core_manager:
    abstract: true
    class: ApiBundle\Manager\CoreManager
    calls:
      - [ setEntityProperties, ["@doctrine.orm.default_entity_manager"] ]
      - [ setTranslator, [ "@translator" ] ]
      - [ setSession, [ "@session" ] ]

  api.product_manager:
    class: "%api.product.class%"
    arguments: [ "%api.product.entity_class%" ]
    parent: api.core_manager